# ドングル（セントラル）設定
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# USB HID 出力（ホストPCへの接続）
# CONFIG_ZMK_USB=y
# CONFIG_ZMK_BLE=y

# Prospector ステータススクリーンを有効化
CONFIG_PROSPECTOR_STATUS_SCREEN_RADII=y
#CONFIG_PROSPECTOR_STATUS_SCREEN_FIELD=y
#CONFIG_PROSPECTOR_STATUS_SCREEN_OPERATOR=y

# Prospector Configuration
CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n
CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=80
CONFIG_PROSPECTOR_LAYER_NAME_UPPERCASE=n
CONFIG_PROSPECTOR_SHOW_MODIFIERS=y


# ペリフェラルのバッテリー残量をセントラルで取得
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y




# ZMK Studio
CONFIG_ZMK_STUDIO=y